modLoader="javafml"
loaderVersion="[${forge_major},)"
license="All Rights Reserved"
clientSideOnly=true

[[mods]]
modId="voicewheel"
version="${version}"
displayName="SimpleVoiceChatScroll"
authors="don4ara"
description='''Adjust Simple Voice Chat player volume with the right mouse button and mouse wheel.'''

[[dependencies.voicewheel]]
modId="forge"
mandatory=true
versionRange="[${forge_major},)"
ordering="NONE"
side="CLIENT"

[[dependencies.voicewheel]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="CLIENT"

[[dependencies.voicewheel]]
modId="voicechat"
mandatory=true
versionRange="[1,)"
ordering="AFTER"
side="CLIENT"
