plugins {
    id 'base'
}

tasks.register('universalJar', Jar) {
    dependsOn ':fabric:remapJar'

    archiveFileName = "${project.archives_base_name}-${project.mod_version}+mc${project.minecraft_version}-universal.jar"
    destinationDirectory = layout.buildDirectory.dir('libs')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from({
        zipTree(project(':fabric').tasks.named('remapJar').get().archiveFile.get().asFile)
    }) {
        exclude 'META-INF/MANIFEST.MF'
    }
    manifest {
        attributes(
                'Fabric-Mapping-Namespace': 'intermediary',
                'Fabric-Minecraft-Version': project.minecraft_version,
                'Fabric-Loader-Version': project.fabric_loader_version
        )
    }
}

tasks.named('assemble') {
    dependsOn tasks.named('universalJar')
}

tasks.named('clean') {
    dependsOn ':fabric:clean'
}
