org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Shared
minecraft_version=1.21.9
java_version=21
mod_version=0.0.2
maven_group=ru.don4ara
archives_base_name=SimpleVoiceChatScroll

# Fabric
loom_version=1.17-SNAPSHOT
fabric_loader_version=0.19.3
fabric_api_version=0.134.1+1.21.9
voicechat_fabric_version=fabric-1.21.9-2.6.4

# Forge
forge_version=59.0.5
voicechat_forge_version=forge-1.21.9-2.6.4

# NeoForge
neoforge_version=21.9.16-beta
voicechat_neoforge_version=neoforge-1.21.9-2.6.4
