org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Shared
minecraft_version=26.1
java_version=25
mod_version=0.0.3
maven_group=ru.don4ara
archives_base_name=SimpleVoiceChatScroll

# Fabric
loom_version=1.17-SNAPSHOT
fabric_loader_version=0.19.3
fabric_api_version=0.145.1+26.1
voicechat_fabric_version=fabric-2.6.14+26.1

# Forge
forge_version=62.0.9
voicechat_forge_version=forge-2.6.14+26.1

# NeoForge
neoforge_version=26.1.0.19-beta
voicechat_neoforge_version=neoforge-2.6.14+26.1
