# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.4
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
java_version=21

# Mod Properties
mod_version=0.0.1
maven_group=ru.don4ara
archives_base_name=voicewheel

# Dependencies
fabric_api_version=0.119.4+1.21.4
voicechat_version=fabric-1.21.4-2.6.21
