modLoader="javafml"
loaderVersion="[3,)"
license="All Rights Reserved"

[[mods]]
modId="voicewheel"
version="${version}"
displayName="SimpleVoiceChatScroll"
authors="don4ara"
displayTest="IGNORE_ALL_VERSION"
description='''
Adjust Simple Voice Chat player volume with right mouse button + mouse wheel.
'''

[[dependencies.voicewheel]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.voicewheel]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},${minecraft_next_version})"
ordering="NONE"
side="CLIENT"

[[dependencies.voicewheel]]
modId="voicechat"
type="required"
versionRange="[2.6.21,)"
ordering="AFTER"
side="CLIENT"
