modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"
clientSideOnly=true

[[mods]]
modId="voicewheel"
version="${version}"
displayName="SimpleVoiceChatScroll"
authors="don4ara"
description='''Adjust Simple Voice Chat player volume with the right mouse button and mouse wheel.'''

[[dependencies.voicewheel]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.voicewheel]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="CLIENT"

[[dependencies.voicewheel]]
modId="voicechat"
type="required"
versionRange="[2.6,)"
ordering="AFTER"
side="CLIENT"
