plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = "${project.mod_version}+mc${project.minecraft_version}"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(
        project.java_version.toString().toInteger()
)

repositories {
    mavenCentral()
    maven {
        url = "https://api.modrinth.com/maven"
    }
}

neoForge {
    version = project.neoforge_version
}

dependencies {
    implementation "maven.modrinth:simple-voice-chat:${project.voicechat_neoforge_version}"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "neoforge_version", project.neoforge_version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand(
                "version": inputs.properties.version,
                "minecraft_version": inputs.properties.minecraft_version,
                "neoforge_version": inputs.properties.neoforge_version
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = project.java_version.toString().toInteger()
}

jar {
    from(rootProject.file("LICENSE")) {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}